# Generated by Django 2.1 on 2020-01-07 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(related_name='followed_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genre',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
