# Generated by Django 2.2 on 2020-01-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200129_2326'),
        ('core', '0002_auto_20200129_1747'),
    ]

    operations = [
    ]
