# Generated by Django 2.1 on 2020-01-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200110_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='genres',
            field=models.ManyToManyField(related_name='questions', to='core.Genre'),
        ),
    ]
