# Generated by Django 2.1 on 2020-01-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
    ]
