# Generated by Django 2.1 on 2020-01-20 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_topic_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 18, 33, 14, 988584)),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 18, 33, 14, 990201)),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 18, 33, 14, 984627)),
        ),
    ]
