# Generated by Django 2.1 on 2020-01-20 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200120_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 18, 39, 3, 680982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 18, 39, 3, 682346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 20, 18, 39, 3, 677881, tzinfo=utc)),
        ),
    ]
